version: '3.7'

services:
  app:  # for develop
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user_name: $user_name
        group_name: $group_name
    image: wsgi
    container_name: wsgi.app
    tty: true
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    ports:
      - "8000:8000"

  gunicorn.falcon:
    image: wsgi
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    command: >
      gunicorn
      --config=conf/gunicorn.ini.py
      --chdir=wsgiapp
      --access-logfile=../log/wsgi/access.grunicorn.falcon.log
      --error-logfile=../log/wsgi/grunicorn.falcon.log
      falconwsgi:api

  gunicorn.flask:
    image: wsgi
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    command: >
      gunicorn
      --config=conf/gunicorn.ini.py
      --chdir=wsgiapp
      --access-logfile=../log/wsgi/access.grunicorn.flask.log
      --error-logfile=../log/wsgi/grunicorn.flask.log
      flaskwsgi:api

  gunicorn.responder:
    image: wsgi
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    command: >
      gunicorn
      -k uvicorn.workers.UvicornWorker
      --config=conf/gunicorn.ini.py
      --chdir=wsgiapp
      --access-logfile=../log/wsgi/access.grunicorn.responder.log
      --error-logfile=../log/wsgi/grunicorn.responder.log
      responderwsgi:api

  uwsgi.falcon:
    image: wsgi
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    command: >
      uwsgi
      --chdir=wsgiapp
      --wsgi-file=falconwsgi.py
      --logto=log/wsgi/uwsgi.falcon.log
      conf/uwsgi.ini

  uwsgi.flask:
    image: wsgi
    volumes:
      - .:/home/$user_name/workspace
    working_dir: /home/$user_name/workspace
    sysctls:
      - net.core.somaxconn=$somaxconn
      - net.ipv4.tcp_syncookies=0
    command: >
      uwsgi
      --chdir=wsgiapp
      --wsgi-file=flaskwsgi.py
      --logto=log/wsgi/uwsgi.flask.log
      conf/uwsgi.ini

  stressor:
    build:
      context: ./stressor
      dockerfile: Dockerfile
    image: stressor
    container_name: stressor
    tty: true
